# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
# https://symfony.com/doc/master/bundles/FOSUserBundle/index.html
security:
    providers:
        fos_userbundle:
            # use both username and email for login
            id: fos_user.user_provider.username_email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                default_target_path: dashboard_index

            logout:       true
            anonymous:    true
            logout_on_user_change: true

    access_control:
        # we normally do access control with annotations in the controllers.
        #- { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: "%secure_channel%" }
        # - { path: ^/login$, host:clanx\.ch$, requires_channel: https }
        # - { path: ^/register, host:clanx\.ch$, requires_channel: https }
        # - { path: ^/resetting/request, host:clanx\.ch$, requires_channel: https }
        # - { path: ^/profile/change-password, roles:ROLE_USER, host:clanx\.ch, requires_channel: https }

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        ROLE_OK:          ROLE_USER
